version: "3.8"

services:
  person-app:
    build: .
    container_name: person-app
    depends_on:
      - person-db
    ports:
      - target: 8080
        published: 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://person-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  person-db:
    image: postgres
    container_name: person-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres